/*
 * MIT License
 * 
 * Copyright (c) 2020-2022 Fabio Lima
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package com.github.f4b6a3.tsid;

import java.io.Serializable;
import java.math.BigInteger;
import java.nio.ByteBuffer;
import java.time.Instant;
import java.util.Arrays;
import java.util.SplittableRandom;
import java.util.concurrent.atomic.AtomicInteger;

/**
 * A value object that represents a Time-Sorted Unique Identifier (TSID).
 * <p>
 * TSID is a 64-bit value that has 2 components:
 * <ul>
 * <li><b>Time component (42 bits)</b>: a number of milliseconds since
 * 1970-01-01 (Unix epoch).
 * <li><b>Random component (22 bits)</b>: a sequence of random bits generated by
 * a secure random generator.
 * </ul>
 * <p>
 * The Random component has 2 sub-parts:
 * <ul>
 * <li><b>Node (0 to 20 bits)</b>: a number used to identify the machine or
 * node.
 * <li><b>Counter (2 to 22 bits)</b>: a randomly generated number that is
 * incremented whenever the time component is repeated.
 * </ul>
 * <p>
 * The random component layout depend on the node bits. If the node bits are 10,
 * the counter bits are limited to 12. In this example, the maximum node value
 * is 2^10-1 = 1023 and the maximum counter value is 2^12-1 = 4093. So the
 * maximum TSIDs that can be generated per millisecond per node is 4096.
 * <p>
 * Instances of this class are <b>immutable</b>.
 *
 * @see <a href="https://en.wikipedia.org/wiki/Snowflake_ID">Snowflake ID</a>
 */
public final class Tsid implements Serializable, Comparable<Tsid> {

    private static final long serialVersionUID = -5446820982139116297L;

    /**
     * The internal value.
     */
    private final long number;

    /**
     * Number of bytes of a TSID.
     */
    public static final int TSID_BYTES = 8;

    /**
     * Number of characters of a TSID.
     */
    public static final int TSID_CHARS = 13;

    /**
     * Number of milliseconds of 2020-01-01T00:00:00.000Z.
     */
    public static final long TSID_EPOCH = Instant.parse("2020-01-01T00:00:00.000Z").toEpochMilli();

    static final int RANDOM_BITS = 22;

    static final int RANDOM_MASK = 0x003fffff;

    static final byte[] ALPHABET_VALUES = new byte[256];

    static final char[] ALPHABET_UPPERCASE = "0123456789ABCDEFGHJKMNPQRSTVWXYZ".toCharArray();

    static final char[] ALPHABET_LOWERCASE = "0123456789abcdefghjkmnpqrstvwxyz".toCharArray();

    static {
        // Initialize the alphabet map with -1
        Arrays.fill(ALPHABET_VALUES, (byte) -1);
        // Map the alphabets chars to values
        for (int i = 0; i < ALPHABET_UPPERCASE.length; i++) {
            ALPHABET_VALUES[ALPHABET_UPPERCASE[i]] = (byte) i;
        }
        for (int i = 0; i < ALPHABET_LOWERCASE.length; i++) {
            ALPHABET_VALUES[ALPHABET_LOWERCASE[i]] = (byte) i;
        }
        // Upper case OIL
        ALPHABET_VALUES['O'] = 0x00;
        ALPHABET_VALUES['I'] = 0x01;
        ALPHABET_VALUES['L'] = 0x01;
        // Lower case OIL
        ALPHABET_VALUES['o'] = 0x00;
        ALPHABET_VALUES['i'] = 0x01;
        ALPHABET_VALUES['l'] = 0x01;
    }

    /**
     * Creates a new TSID.
     * <p>
     * This constructor wraps the input value in an immutable object.
     *
     * @param number a number
     */
    public Tsid(final long number) {
        this.number = number;
    }

    /**
     * Converts a number into a TSID.
     * <p>
     * This method wraps the input value in an immutable object.
     *
     * @param number a number
     * @return a TSID
     */
    public static Tsid from(final long number) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Converts a byte array into a TSID.
     *
     * @param bytes a byte array
     * @return a TSID
     * @throws IllegalArgumentException if bytes are null or its length is not 8
     */
    public static Tsid from(final byte[] bytes) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Converts a canonical string into a TSID.
     * <p>
     * The input string must be 13 characters long and must contain only characters
     * from Crockford's base 32 alphabet.
     * <p>
     * The first character of the input string must be between 0 and F.
     *
     * @param string a canonical string
     * @return a TSID
     * @throws IllegalArgumentException if the input string is invalid
     * @see <a href="https://www.crockford.com/base32.html">Crockford's Base 32</a>
     */
    public static Tsid from(final String string) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Converts the TSID into a number.
     * <p>
     * This method simply unwraps the internal value.
     *
     * @return an number.
     */
    public long toLong() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Converts the TSID into a byte array.
     *
     * @return an byte array.
     */
    public byte[] toBytes() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Returns a fast new TSID.
     * <p>
     * This static method is a quick alternative to {@link TsidCreator#getTsid()}.
     * <p>
     * It employs {@link AtomicInteger} to generate up to 2^22 (4,194,304) TSIDs per
     * millisecond. It can be useful, for example, for logging.
     * <p>
     * Security-sensitive applications that require a cryptographically secure
     * pseudo-random generator <b>should</b> use {@link TsidCreator#getTsid()}.
     * <p>
     * System property "tsidcreator.node" and environment variable
     * "TSIDCREATOR_NODE" are ignored by this method. Therefore, there will be
     * collisions if more than one process is generating TSIDs using this method. In
     * that case, {@link TsidCreator#getTsid()} <b>should</b> be used in conjunction
     * with that property or variable.
     *
     * @return a TSID
     * @since 5.1.0
     */
    public static Tsid fast() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Converts the TSID into a canonical string in upper case.
     * <p>
     * The output string is 13 characters long and contains only characters from
     * Crockford's base 32 alphabet.
     * <p>
     * For lower case string, use the shorthand {@code Tsid.toLowerCase()} instead
     * of {@code Tsid.toString().toLowerCase()}.
     *
     * @return a TSID string
     * @see <a href="https://www.crockford.com/base32.html">Crockford's Base 32</a>
     */
    @Override
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Converts the TSID into a canonical string in lower case.
     * <p>
     * The output string is 13 characters long and contains only characters from
     * Crockford's base 32 alphabet.
     * <p>
     * It is faster shorthand for {@code Tsid.toString().toLowerCase()}.
     *
     * @return a string
     * @see <a href="https://www.crockford.com/base32.html">Crockford's Base 32</a>
     */
    public String toLowerCase() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Returns the instant of creation.
     * <p>
     * The instant of creation is extracted from the time component.
     *
     * @return {@link Instant}
     */
    public Instant getInstant() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Returns the instant of creation.
     * <p>
     * The instant of creation is extracted from the time component.
     *
     * @param customEpoch the custom epoch instant
     * @return {@link Instant}
     */
    public Instant getInstant(final Instant customEpoch) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Returns the time of creation in milliseconds since 1970-01-01.
     * <p>
     * The time of creation is extracted from the time component.
     *
     * @return the number of milliseconds since 1970-01-01
     */
    public long getUnixMilliseconds() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Returns the time of creation in milliseconds since 1970-01-01.
     * <p>
     * The time of creation is extracted from the time component.
     *
     * @param customEpoch the custom epoch in milliseconds since 1970-01-01
     * @return the number of milliseconds since 1970-01-01
     */
    public long getUnixMilliseconds(final long customEpoch) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Returns the time component as a number.
     * <p>
     * The time component is a number between 0 and 2^42-1.
     *
     * @return a number of milliseconds.
     */
    long getTime() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Returns the random component as a number.
     * <p>
     * The time component is a number between 0 and 2^22-1.
     *
     * @return a number
     */
    long getRandom() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Checks if the input string is valid.
     * <p>
     * The input string must be 13 characters long and must contain only characters
     * from Crockford's base 32 alphabet.
     * <p>
     * The first character of the input string must be between 0 and F.
     *
     * @param string a string
     * @return true if valid
     */
    public static boolean isValid(final String string) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Returns a hash code value for the TSID.
     */
    @Override
    public int hashCode() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Checks if some other TSID is equal to this one.
     */
    @Override
    public boolean equals(Object other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Compares two TSIDs as <b>unsigned</b> 64-bit integers.
     * <p>
     * The first of two TSIDs is greater than the second if the most significant
     * byte in which they differ is greater for the first TSID.
     *
     * @param that a TSID to be compared with
     * @return -1, 0 or 1 as {@code this} is less than, equal to, or greater than
     *         {@code that}
     */
    @Override
    public int compareTo(Tsid that) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Converts the TSID to a base-n encoded string.
     * <p>
     * Example:
     * <ul>
     * <li>TSID: 0AXS751X00W7C
     * <li>Base: 62
     * <li>Output: 0T5jFDIkmmy
     * </ul>
     * <p>
     * The output string is left padded with zeros.
     *
     * @param base a radix between 2 and 62
     * @return a base-n encoded string
     * @throws IllegalArgumentException if the base is invalid
     * @since 5.2.0
     */
    public String encode(final int base) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Converts a base-n encoded string to a TSID.
     * <p>
     * Example:
     * <ul>
     * <li>String: 05772439BB9F9074
     * <li>Base: 16
     * <li>Output: 0AXS476XSZ43M
     * </ul>
     * <p>
     * The input string must be left padded with zeros.
     * <p>
     * <b>Note</b>: this method is CASE-SENSITIVE.
     *
     * @param string a base-n encoded string
     * @param base   a radix between 2 and 62
     * @return a TSID
     * @throws IllegalArgumentException if the string or base is invalid
     * @since 5.2.0
     */
    public static Tsid decode(final String string, final int base) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Converts the TSID to a string using a custom format.
     * <p>
     * The custom format uses a placeholder that will be substituted by the TSID
     * string. Only the first occurrence of a placeholder will replaced.
     * <p>
     * Placeholders:
     * <ul>
     * <li>%S: canonical string in upper case
     * <li>%s: canonical string in lower case
     * <li>%X: hexadecimal in upper case
     * <li>%x: hexadecimal in lower case
     * <li>%d: base-10
     * <li>%z: base-62
     * </ul>
     * <p>
     * Examples:
     * <ul>
     * <li>An key that starts with a letter:
     * <ul>
     * <li>TSID: 0AWE5HZP3SKTK
     * <li>Format: K%S
     * <li>Output: K<b>0AWE5HZP3SKTK</b>
     * </ul>
     * </li>
     * <li>A file name in hexadecimal with a prefix and an extension:
     * <ul>
     * <li>TSID: 0AXFXR5W7VBX0
     * <li>Format: DOC-%X.PDF
     * <li>Output: DOC-<b>0575FDC1786137D6</b>.PDF
     * </ul>
     * </li>
     * </ul>
     * <p>
     * The opposite operation can be done by {@link Tsid#unformat(String, String)}.
     *
     * @param format a custom format
     * @return a string using a custom format
     * @throws IllegalArgumentException if the format string is invalid
     * @since 5.2.0
     */
    public String format(final String format) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Converts a string using a custom format to a TSID.
     * <p>
     * This method does the opposite operation of {@link Tsid#format(String)}.
     * <p>
     * Examples:
     * <ul>
     * <li>An key that starts with a letter:
     * <ul>
     * <li>String: K<b>0AWE5HZP3SKTK</b>
     * <li>Format: K%S
     * <li>Output: 0AWE5HZP3SKTK
     * </ul>
     * </li>
     * <li>A file name in hexadecimal with a prefix and an extension:
     * <ul>
     * <li>String: DOC-<b>0575FDC1786137D6</b>.PDF
     * <li>Format: DOC-%X.PDF
     * <li>Output: 0AXFXR5W7VBX0
     * </ul>
     * </li>
     * </ul>
     *
     * @param formatted a string using a custom format
     * @param format    a custom format
     * @return a TSID
     * @throws IllegalArgumentException if the formatted string or the format string
     *                                  is invalid
     * @since 5.2.0
     */
    public static Tsid unformat(final String formatted, final String format) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    String toString(final char[] alphabet) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    static char[] toCharArray(final String string) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Checks if the string is a valid TSID.
     *
     * A valid TSID string is a sequence of 13 characters from Crockford's base 32
     * alphabet.
     *
     * The first character of the input string must be between 0 and F.
     *
     * @param chars a char array
     * @return boolean true if valid
     */
    static boolean isValidCharArray(final char[] chars) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    static class BaseN {

        static final BigInteger MAX = BigInteger.valueOf(2).pow(64).subtract(BigInteger.ONE);

        // base-62
        static final String ALPHABET = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";

        static String encode(final Tsid tsid, final int base) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        static Tsid decode(final String string, final int base) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        private static int length(int base) {
            return (int) Math.ceil(Long.SIZE / (Math.log(base) / Math.log(2)));
        }

        private static void exception(String string) {
            throw new IllegalArgumentException(string);
        }
    }

    private static class LazyHolder {

        private static final AtomicInteger counter = new AtomicInteger((new SplittableRandom()).nextInt());
    }
}
